let
    //Load the Customer dataset
    Source = Excel.Workbook(File.Contents("C:\Users\revat\Downloads\coffeeOrdersData.xlsx"), null, true),
    customers_Sheet = Source{[Item="customers",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(customers_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Customer Name", type text}, {"Email", type text}, {"Phone Number", type text}, {"Address Line 1", type text}, {"City", type text}, {"Country", type text}, {"Postcode", type any}, {"Loyalty Card", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Address Line 1", "Postcode", "Phone Number"})

    //Load Products dataset
    Source = Excel.Workbook(File.Contents("C:\Users\revat\Downloads\coffeeOrdersData.xlsx"), null, true),
    products_Sheet = Source{[Item="products",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(products_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product ID", type text}, {"Coffee Type", type text}, {"Roast Type", type text}, {"Size", type number}, {"Unit Price", type number}, {"Price per 100g", type number}, {"Profit", type number}})


    //Load Orders dataset
    Source = Excel.Workbook(File.Contents("C:\Users\revat\Downloads\coffeeOrdersData.xlsx"), null, true),
    orders_Sheet = Source{[Item="orders",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(orders_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order ID", type text}, {"Order Date", type date}, {"Customer ID", type text}, {"Product ID", type text}, {"Quantity", Int64.Type}, {"Customer Name", type any}, {"Email", type any}, {"Country", type any}, {"Coffee Type", type any}, {"Roast Type", type any}, {"Size", type any}, {"Unit Price", type any}, {"Sales", type any}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Customer Name", "Email", "Country", "Coffee Type", "Roast Type", "Size", "Unit Price", "Sales"}),
    
    // Calculated Date Column for Month
    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Month", each Date.MonthName([Order Date])),

    // Calculated Date Column for Year
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Year", each Date.Year([Order Date])),

    // Calculated Date Column for Day
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Day", each Date.DayOfWeekName([Order Date],"dd")),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"Day", type text}, {"Year", Int64.Type}, {"Month", type text}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type1", {"Product ID"}, products, {"Product ID"}, "products", JoinKind.Inner),
    #"Expanded products" = Table.ExpandTableColumn(#"Merged Queries", "products", {"Unit Price", "Price per 100g"}, {"products.Unit Price", "products.Price per 100g"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expanded products",{"Order ID", "Order Date", "Customer ID", "Product ID", "products.Unit Price", "products.Price per 100g", "Quantity", "Month", "Year", "Day"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Reordered Columns",{{"products.Unit Price", Currency.Type}, {"products.Price per 100g", Currency.Type}}),

    // Calculated Sales Amount
    #"Added Custom3" = Table.AddColumn(#"Changed Type2", "Sales_Amt", each [Quantity]*[products.Unit Price]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom3",{{"Sales_Amt", type number}})
in
    #"Removed Columns"
in
    #"Changed Type"
in
    #"Changed Type3"